### ISSUE TITLE
No module named click

### ISSUE THREAD

**Issue by supermindsv1** [foxlet/macOS-Simple-KVM#260]
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.18.4)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (7.1.2)
Traceback (most recent call last):
  File "fetch-macos.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'

This issue is coming up every time I run the ./jumpstart.sh and I have tried everything mentioned in the Issues. Please tell the fix or (if possible) please give the download link to the BaseSystem file.

PS I am using Linux Mint 19.3 and am a new user.

**Comment by imnotadam** [comment]
try pip install click, pip3 install click, python -m pip install click or python3 -m pip install click

**Comment by supermindsv1** [comment]
I already did those. None of them worked. That is why I raised this issue.

**Comment by supermindsv1** [comment]
Quick Update.... I used a snap called Sosumi and it worked perfectly. This snap is based on this project. Currently installing MacOS. Needed ot for XCode.

**Comment by buriedaliveIX** [comment]
I confirm. Gentoo Linux. I already have installed package dev-python/click, but ...
-------
./jumpstart.sh --mojave
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.23.0)
Requirement already satisfied: click in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (7.1.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (2020.4.5.1)
Traceback (most recent call last):
  File "fetch-macos.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'
-------
Project into Trash Can. Need fix for click.

**Comment by supermindsv1** [comment]
Did you try the snap I mentioned. There is a derailed guide on linuxuprising.com

**Comment by buriedaliveIX** [comment]
> Did you try the snap I mentioned. There is a derailed guide on linuxuprising.com

Tnx, but I don't need an any snap.

**Comment by buriedaliveIX** [comment]
The first thing I did changed line 1 in file fetch-macos.py "#!/usr/bin/python" to "#!/usr/bin/env python".
After that need to adjust default python interpreters. In Gentoo Linux: eselect python list, eselect python set 3 (for example),  
eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.6 (uninstalled)
  [2]   python3.8 (fallback)
  [3]   python3.7 (fallback)
  [4]   python2.7 (fallback)
In Ubuntu/Debian/Mint to change python version system-wide we can use update-alternatives command.
Also check that python and pip versions had the same.
For me now:
python --version
Python 3.7.7
pip --version
pip 20.0.2 from /usr/lib/python3.7/site-packages/pip (python 3.7)
All these actions helped me. The problem is solved.
