### ISSUE TITLE
dmg image is corrupted 

### ISSUE THREAD

**Issue by EmmanuelZapata** [foxlet/macOS-Simple-KVM#285]
Hey everyone,

I'm getting this error below:
sudo ./jumpstart.sh
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: click in /root/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (7.1.2)
2020-07-20 18:01:44,613 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
2020-07-20 18:01:45,285 Network Request: Fetching http://swcdn.apple.com/content/downloads/41/23/061-26578-A_FF0C6M87LS/ylvl0phx6uy3i444qt9p57n8wz0xnylmd9/InstallAssistantAuto.smd
2020-07-20 18:01:45,469 Network Request: Fetching http://swcdn.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/InstallAssistantAuto.smd
2020-07-20 18:01:46,130 Network Request: Fetching http://swcdn.apple.com/content/downloads/06/50/041-91758-A_M8T44LH2AW/b5r4og05fhbgatve4agwy4kgkzv07mdid9/InstallAssistantAuto.smd
2020-07-20 18:01:46,197 Network Request: Fetching http://swcdn.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/InstallAssistantAuto.smd
2020-07-20 18:01:46,260 Network Request: Fetching http://swcdn.apple.com/content/downloads/08/44/041-90855-A_452WLVQACP/mzfvoi59bljh3w4w4lvwenfk0r1a2f7212/InstallAssistantAuto.smd
2020-07-20 18:01:46,316 Network Request: Fetching http://swcdn.apple.com/content/downloads/01/28/061-86291-A_JPEIWIOZES/enpozvvbmj3mj2dhulhevlt8b429qd5kw0/InstallAssistantAuto.smd
2020-07-20 18:01:46,419 Network Request: Fetching http://swcdn.apple.com/content/downloads/37/41/001-04366/a6boefh8b6bee4k2x6v5lwyfjr7od2ica3/InstallAssistantAuto.smd
2020-07-20 18:01:46,540 Network Request: Fetching http://swcdn.apple.com/content/downloads/59/18/001-15219-A_EE9FN7UHJA/efuz3h0zlmx4qlinf4bxlguigo9jvhcr55/InstallAssistantAuto.smd
2020-07-20 18:01:46,658 Network Request: Fetching http://swcdn.apple.com/content/downloads/41/56/061-94403-A_5AM6QB8TGK/ijdhki76d4rw19t579eblaqc26ngzlhu1p/InstallAssistantAuto.smd
2020-07-20 18:01:46,970 Selected macOS Product: 061-86291

dmg2img v1.6.7 (c) vu1tur (to@vu1tur.eu.org)

ERROR: dmg image is corrupted
Doesn't matter what OS I try. I get dmg image corrupted.  I've tried deleting and trying several times... no go.

**Comment by jaredpooole** [comment]
Same issue here...

**Comment by rathinasamyt** [comment]
i am seeing the same issue as well.

**Comment by jf352** [comment]
Apple appears to be aborting the downloads early. What you can do is modify one of the python scripts and to print the download URL before it actually downloads, then use a resume-capable tool like aria2 to download the BaseSystem.dmg

**Comment by jkopec** [comment]
After getting the `ERROR: dmg image is corrupted` issue, I get the following now:

```
2020-07-21 10:24:21,173 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
2020-07-21 10:24:22,149 Network Request: Fetching http://swcdn.apple.com/content/downloads/41/23/061-26578-A_FF0C6M87LS/ylvl0phx6uy3i444qt9p57n8wz0xnylmd9/InstallAssistantAuto.smd
2020-07-21 10:24:22,197 Network Request: Fetching http://swcdn.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/InstallAssistantAuto.smd
2020-07-21 10:24:22,209 Network Request: Fetching http://swcdn.apple.com/content/downloads/06/50/041-91758-A_M8T44LH2AW/b5r4og05fhbgatve4agwy4kgkzv07mdid9/InstallAssistantAuto.smd
2020-07-21 10:24:22,219 Network Request: Fetching http://swcdn.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/InstallAssistantAuto.smd
2020-07-21 10:24:22,230 Network Request: Fetching http://swcdn.apple.com/content/downloads/08/44/041-90855-A_452WLVQACP/mzfvoi59bljh3w4w4lvwenfk0r1a2f7212/InstallAssistantAuto.smd
2020-07-21 10:24:22,239 Network Request: Fetching http://swcdn.apple.com/content/downloads/01/28/061-86291-A_JPEIWIOZES/enpozvvbmj3mj2dhulhevlt8b429qd5kw0/InstallAssistantAuto.smd
2020-07-21 10:24:22,254 Network Request: Fetching http://swcdn.apple.com/content/downloads/37/41/001-04366/a6boefh8b6bee4k2x6v5lwyfjr7od2ica3/InstallAssistantAuto.smd
2020-07-21 10:24:22,266 Network Request: Fetching http://swcdn.apple.com/content/downloads/59/18/001-15219-A_EE9FN7UHJA/efuz3h0zlmx4qlinf4bxlguigo9jvhcr55/InstallAssistantAuto.smd
2020-07-21 10:24:22,280 Network Request: Fetching http://swcdn.apple.com/content/downloads/41/56/061-94403-A_5AM6QB8TGK/ijdhki76d4rw19t579eblaqc26ngzlhu1p/InstallAssistantAuto.smd
2020-07-21 10:24:22,569 Selected macOS Product: 061-86291
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fetch-macos.py", line 165, in <module>
    fetchmacos()
  File "/root/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "fetch-macos.py", line 162, in fetchmacos
    product.fetchpackages(output_dir, keyword=keyword)
  File "fetch-macos.py", line 132, in fetchpackages
    Filesystem.download_file(item.get("URL"), item.get("Size"), path)
  File "fetch-macos.py", line 35, in download_file
    remote = requests.get(url, stream=True, headers=ClientMeta.osinstall)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
Seems like Apple aborts image downloads?

**Comment by jf352** [comment]
There should be a way, in python, to run requests.get and then, if an exception occurs when downloading, get the filesize you've downloaded so far, and then resuming the download from that position in a while loop

Not sure how that would actually be implemented, in terms of code, though. it seems to start the download at least

**Comment by garrett** [comment]
BTW, as a follow-up to @jf352's [comment](https://github.com/foxlet/macOS-Simple-KVM/issues/285#issuecomment-661702317) If you want to see the URL being downloaded, add:
```python
        print(url, file = sys.stderr)
```

Right above ` # Set to stream mode for large files` in `tools/FetchMacOS/fetch-macos.py`

**Comment by jf352** [comment]
I've got a potential "fix" ready (instead of doing a single write to file, it'll continually append, and in the event of a failure, retry with resume) but still in testing stages

**Comment by gaurav-nelson** [comment]
The error shows up because the downloaded `dmg` file is incomplete. I was getting the same error, looks like apple is blocking the download or they must be having some issues. I tried with VPN and was able to download the `dmg` file in the third try.
1. VPN Australia -> fail
2. VPN USA -> fail
3. VPN Singapore -> pass

@jkopec Just restart your terminal and it will go away. 

Also, I used https://github.com/kholia/OSX-KVM/blob/master/fetch-macOS.py to download the image, it shows the URL by default.

But, later I got stuck on installing OSX, getting the `PKDownloadError error 8`. Which is another error related to network connection. (https://apple.stackexchange.com/questions/372785/pkdownloaderror-error-8-upon-catalina-update)

**Comment by EmmanuelZapata** [comment]
It now worked for me.  I think maybe Cloudflare outage messed it up?

**Comment by jkopec** [comment]
I tried it a few hours later yesterday and it worked even without a VPN. Could also successfully install macOS Catalina. Seems like a time related Apple network / Cloudflare issue to me. :)

**Comment by foxlet** [comment]
Yeah, there were some Apple CDN issues (including application signing) earlier in the week. If it's still ongoing please note it here, otherwise feel free to close the issue. Thanks!

**Comment by shahidcodes** [comment]
Some issue with the CDN happened the same with me. I just let it redownload and it worked fine.
