### ISSUE TITLE
Running JumpStart Fails

### ISSUE THREAD

**Issue by bu3alwa** [foxlet/macOS-Simple-KVM#317]
Just fails on the first step
Info:
> == Distro Info ==
> LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
> Distributor ID:	Fedora
> Description:	Fedora release 32 (Thirty Two)
> Release:	32
> Codename:	ThirtyTwo
> == Loaded Modules ==
> kvm_amd               114688  0
> kvm                   823296  1 kvm_amd
> ccp                   106496  1 kvm_amd
> irqbypass              16384  2 vfio_pci,kvm
> == Installed Binaries ==
> QEMU emulator version 4.2.1 (qemu-4.2.1-1.fc32)
> Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
> virt-manager version 2.2.1
> Python 3.8.5
> pip 19.3.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)

Error:
> Traceback (most recent call last):
>   File "fetch-macos.py", line 158, in <module>
>     fetchmacos()
>   File "/home/carbon/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/carbon/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/carbon/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/carbon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "fetch-macos.py", line 143, in fetchmacos
>     product_id = remote.getosinstall()[0]
>   File "fetch-macos.py", line 107, in getosinstall
>     if self.version in Filesystem.parse_plist(Filesystem.fetch_plist(meta_url)).get('CFBundleShortVersionString', {}):
>   File "fetch-macos.py", line 61, in parse_plist
>     root = plistlib.loads(catalog_data)
>   File "/usr/lib64/python3.8/plistlib.py", line 1000, in loads
>     return load(
>   File "/usr/lib64/python3.8/plistlib.py", line 986, in load
>     raise InvalidFileException()
> plistlib.InvalidFileException: Invalid file

**Comment by md-shah** [comment]
Yes, I do have the same issue while running jumstart.sh 

Error Log: 
```
`./jumpstart.sh --catalina
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (7.0)
2020-10-11 19:03:16,134 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
2020-10-11 19:03:19,578 Network Request: Fetching http://swcdn.apple.com/content/downloads/41/23/061-26578-A_FF0C6M87LS/ylvl0phx6uy3i444qt9p57n8wz0xnylmd9/InstallAssistantAuto.smd
2020-10-11 19:03:19,905 Network Request: Fetching http://swcdn.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/InstallAssistantAuto.smd
2020-10-11 19:03:20,101 Network Request: Fetching http://swcdn.apple.com/content/downloads/06/50/041-91758-A_M8T44LH2AW/b5r4og05fhbgatve4agwy4kgkzv07mdid9/InstallAssistantAuto.smd
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 388, in _decode
    data = self._decoder.decompress(data)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 85, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 536, in read
    data = self._decode(data, decode_content, flush_decoder)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 391, in _decode
    raise DecodeError(
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fetch-macos.py", line 158, in <module>
    fetchmacos()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "fetch-macos.py", line 143, in fetchmacos
    product_id = remote.getosinstall()[0]
  File "fetch-macos.py", line 107, in getosinstall
    if self.version in Filesystem.parse_plist(Filesystem.fetch_plist(meta_url)).get('CFBundleShortVersionString', {}):
  File "fetch-macos.py", line 54, in fetch_plist
    plist_raw = requests.get(url, headers=ClientMeta.swupdate)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/lib/python3/dist-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3/dist-packages/requests/models.py", line 755, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))`
```

**Comment by gaoyifan** [comment]
modify `fetch-macos.py` helps me solve the problem
```python
def get_default_catalog():
    '''Returns the default softwareupdate catalog for the current OS'''
    #return catalogs["20"]
    return catalogs["PublicRelease"]
```
