### ISSUE TITLE
zlib error

### ISSUE THREAD

**Issue by jay-goyal** [foxlet/macOS-Simple-KVM#331]
When I try to run jumpstart.sh, I get a huge error which I could not fix.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 399, in _decode
    data = self._decoder.decompress(data)
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 86, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 575, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 547, in read
    data = self._decode(data, decode_content, flush_decoder)
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 402, in _decode
    raise DecodeError(
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fetch-macos.py", line 159, in <module>
    fetchmacos()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "fetch-macos.py", line 144, in fetchmacos
    product_id = remote.getosinstall()[0]
  File "fetch-macos.py", line 108, in getosinstall
    if self.version in Filesystem.parse_plist(Filesystem.fetch_plist(meta_url)).get('CFBundleShortVersionString', {}):
  File "fetch-macos.py", line 55, in fetch_plist
    plist_raw = requests.get(url, headers=ClientMeta.swupdate)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 685, in send
    r.content
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 756, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
```

**Comment by divyanshugarg36** [comment]
Facing the very same problem if u solved it please help!!

**Comment by jay-goyal** [comment]
I could not fix this error but I got MacOS Catalina working through another fantastic tutorial... https://sick.codes/how-to-install-macos-virtual-machine-on-linux-arch-manjaro-catalina-mojave-or-high-sierra-xcode-working/ Here is the link... Also you might want to try a snap called Sosumi. It is based on the same project but since I am not going to install snapd on my install, I can't comment on if it will work.
