### ISSUE TITLE
problem with virt manager

### ISSUE THREAD

**Issue by ghost** [foxlet/macOS-Simple-KVM#379]
When I Ever try to launch MacOS from virt-manager it gives me this error message

**Error starting domain: Cannot access storage file '/run/media/sinshro/b0652bcd-3782-4a92-9349-13bdd08944c7/MacVM/macOS-Simple-KVM/MyDisk.qcow2' (as uid:65534, gid:992): Permission denied**
Error starting domain: Cannot access storage file '/run/media/sinshro/b0652bcd-3782-4a92-9349-13bdd08944c7/MacVM/macOS-Simple-KVM/MyDisk.qcow2' (as uid:65534, gid:992): Permission denied
**Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 101, in tmpcb
    callback(*args, **kwargs)
  **File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args,** **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1330, in startup
    self._backend.create()
  File "/usr/lib/python3.8/site-packages/libvirt.py", line 1234, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: Cannot access storage file '/run/media/sinshro/b0652bcd-3782-4a92-9349-13bdd08944c7/MacVM/macOS-Simple-KVM/MyDisk.qcow2' (as uid:65534, gid:992): Permission denied**

I tried changing the permissions but nothing worked

Machine:Manjaro linux x86_64

**Comment by unloopedmido** [comment]
Try using root (```sudo```)

**Comment by ghost** [comment]
Tried that same thing

**Comment by unloopedmido** [comment]
I think this can help:
https://github.com/foxlet/macOS-Simple-KVM/issues/84

**Comment by bishoyroufael** [comment]
I had a similar scenario. You probably created your storage on an external partition that is currently mounted to `/media` . Running with `sudo` won't fix it the only option is to change your mounting point to somewhere else. You can do that by going to the genome disk application, click in the partition where your storage is, and edit the mounting point from the settings. *i.e Disable the app defaults in order to change the mounting point manually*

 In my case, I changed it to `/mnt`. Don't forget to edit all the config files where your path to the storage was needed.

**Comment by uualid** [comment]
@b15h0y Thanks!! This error was a lot of unnecessary pain.
