### ISSUE TITLE
Ubuntu 16.04 (python 3.5)  ./jumpstart.sh  fails

### ISSUE THREAD

**Issue by ouboub** [foxlet/macOS-Simple-KVM#392]
Hi

I clone the repository and run 
/jumpstart.sh
to obtain

Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
Traceback (most recent call last):
  File "fetch-macos.py", line 9, in <module>
    import click
ImportError: No module named 'click'

is my python 3.5 installation too old?

What can I do

**Comment by btallin** [comment]
It looks like you're just missing the click library. Can you run ```pip3 list | grep click```? If it doesn't return anything then you can install it by runnimg ```pip3 install --user click```. NOTE: changing your system python environment could have unwanted side effects so proceed with caution and backup before hand.

**Comment by ouboub** [comment]
>>> "BT" == Ben Tallin <notifications@github.com> writes:

> It looks like you're just missing the click library. Can you run
> ```pip3 list | grep click```? If it doesn't return anything then you
> can install it by runnimg ```pip3 install --user click```. NOTE:
> changing your system python environment could have unwanted side
> effects so proceed with caution and backup before hand.

I think there is a problem with pip3

pip3 list | grep click
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'


Not sure how to proceed.

**Comment by Masamune3210** [comment]
pip is broken in your install if not python entirely. Unless something is special about your environment it might just be easier to uninstall and reinstall python and pip and try again
