### ISSUE TITLE
unable to find any master var store for loader

### ISSUE THREAD

**Issue by galtline** [foxlet/macOS-Simple-KVM#395]
I can still launch from Basic.SH but I am not able to load from Virtual Machine. I followed the directions here:

https://passthroughpo.st/new-and-improved-mac-os-tutorial-part-1-the-basics/#disqus_thread

When I start the Virtual machine from VMM.

Error starting domain: operation failed: unable to find any master var store for loader: /Documents/macOS-Simple-KVM/firmware/OVMF_CODE.fd

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1279, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1234, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: operation failed: unable to find any master var store for loader: /Documents/macOS-Simple-KVM/firmware/OVMF_CODE.fd

**Comment by mike-lloyd03** [comment]
I was having the same problem but I figured it out. For some reason, git cloning the repo does not include [OVMF_VARS-1024x768.fd](https://github.com/foxlet/macOS-Simple-KVM/blob/master/firmware/OVMF_VARS-1024x768.fd). Downloading the file and moving it into the `firmware` directory fixed the problem.

**Comment by Sepehr13** [comment]
i'm having the same problem and the file "OVMF_VARS-1024x768.fd" exists but the error is still there

`Error starting domain: operation failed: unable to find any master var store for loader: "/media/sepehr/Local Disk/MacKVM/macOS-Simple-KVM/firmware/OVMF_CODE.fd"

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1279, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1234, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: operation failed: unable to find any master var store for loader: "/media/sepehr/Local Disk/MacKVM/macOS-Simple-KVM/firmware/OVMF_CODE.fd"`

**Comment by richterlevania3** [comment]
Had this same problem. Manjaro Linux on a Ryzen 3600X. One entire SSD for it. At this point I will just leave it.

**Comment by quisys** [comment]
bump, still broken

**Comment by HaleTom** [comment]
My error message specified `$HOME/OSX-KVM/OVMF_CODE.fd` which didn't exist because I didn't `git clone` under `$HOME`.  I moved symlinked to the correct directory and the error went away.

Is there any way of setting the expected directory?

**Comment by BongSolo** [comment]
> My error message specified `$HOME/OSX-KVM/OVMF_CODE.fd` which didn't exist because I didn't `git clone` under `$HOME`. I moved symlinked to the correct directory and the error went away.
> 
> Is there any way of setting the expected directory?

i had same issue i ended up editing the xml file finding all the entries with $HOME/OSX-KVM/ with whatever dir my files are in. Hope this makes sense.

**Comment by ghost** [comment]
On Mint 20.1:
Error starting domain: operation failed: unable to find any master var store for loader: /home/frederic/macOS-Simple-KVM/firmware/OVMF_CODE.fd

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1279, in startup

**Comment by OmkoBass** [comment]
You might be able to fix this by using
```sudo ./make.sh --add``` 
instead of 
```./make.sh --add```

**Comment by ghost** [comment]
Thank you very much!

**Comment by cilahn** [comment]
First foxlet thank you for your hard work going into this. Second, i could trigger this bug when using virt-manager. If you delete the virtual machine added via sudo ./make --add the and allow virt-manager to delete all files the 'OVMF_VARS-1024x768.fd' gets deleted too - even it's not listed for deletion. 
Hope it helps a bit.

**Comment by notAperson535** [comment]
@cilahn I wouldn't let virt-manager delete the files

**Comment by fredericodevbtw** [comment]
> 

This fixed the error for me, thanks @cilahn!
