### ISSUE TITLE
Did not get big sur running

### ISSUE THREAD

**Issue by nemihome** [foxlet/macOS-Simple-KVM#397]
I tried to adapt the files fetch-macos.py and jumpstart.sh for bigsur Installation but was not successful:

```
    catalogs = {
                "11": {              
                    "CustomerSeed":"https://swscan.apple.com/content/catalogs/others/index-11customerseed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
                    "DeveloperSeed":"https://swscan.apple.com/content/catalogs/others/index-11seed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
                    "PublicSeed":"https://swscan.apple.com/content/catalogs/others/index-11beta-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
                    "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-11-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
                        },
                "10.16": {
                    "CustomerSeed":"https://swscan.apple.com/content/catalogs/others/index-10.16customerseed-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
                    "DeveloperSeed":"https://swscan.apple.com/content/catalogs/others/index-10.16seed-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
                    "PublicSeed":"https://swscan.apple.com/content/catalogs/others/index-10.16beta-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
                    "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
                        },  
                "10.15": {                
                    "CustomerSeed":"https://swscan.apple.com/content/catalogs/others/index-10.15customerseed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
                    "DeveloperSeed":"https://swscan.apple.com/content/catalogs/others/index-10.15seed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
                    "PublicSeed":"https://swscan.apple.com/content/catalogs/others/index-10.15beta-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
                    "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
#                "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-11-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
                        },
                "10.14": {
                    "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
                        },
                "10.13": {
                    "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
                        }
                }
```

```
argument="$1"
case $argument in
    -h|--help)
        print_usage
        ;;
    -s|--high-sierra)
        "$TOOLS/FetchMacOS/fetch.sh" -v 10.13 || exit 1;
        ;;
    -m|--mojave)
        "$TOOLS/FetchMacOS/fetch.sh" -v 10.14 || exit 1;
        ;;
    -b|--bigsur)
        "$TOOLS/FetchMacOS/fetch.sh" -v 10.16 || exit 1;
        ;;
    -d|--bigsurd)
        "$TOOLS/FetchMacOS/fetch.sh" -v 11 || exit 1;
        ;;        
    -c|--catalina|*)
        "$TOOLS/FetchMacOS/fetch.sh" -v 10.15 || exit 1;
        ;;
esac
```

Result is for using the option -d or -b is:
2021-01-04 18:27:09,403 Network Request: Fetching http://swcdn.apple.com/content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/InstallAssistantAuto.smd
Traceback (most recent call last):
  File "fetch-macos.py", line 171, in <module>
    fetchmacos()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "fetch-macos.py", line 156, in fetchmacos
    product_id = remote.getosinstall()[0]
IndexError: list index out of range

I also tried to create a harddisk with installer of big sur. The installation from this disk is also not working with simple-kvm because starting the big sur installer harddisk the vm will stuck in boot process. The same disk with big sur installer will work with OSX-KVM. But OSX-KVM has horrible graphics performance and no sound.

**Comment by Umeaboy** [comment]
> I tried to adapt the files fetch-macos.py and jumpstart.sh for bigsur Installation but was not successful:
> 
> ```
>     catalogs = {
>                 "11": {              
>                     "CustomerSeed":"https://swscan.apple.com/content/catalogs/others/index-11customerseed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
>                     "DeveloperSeed":"https://swscan.apple.com/content/catalogs/others/index-11seed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
>                     "PublicSeed":"https://swscan.apple.com/content/catalogs/others/index-11beta-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
>                     "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-11-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
>                         },
>                 "10.16": {
>                     "CustomerSeed":"https://swscan.apple.com/content/catalogs/others/index-10.16customerseed-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
>                     "DeveloperSeed":"https://swscan.apple.com/content/catalogs/others/index-10.16seed-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
>                     "PublicSeed":"https://swscan.apple.com/content/catalogs/others/index-10.16beta-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
>                     "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
>                         },  
>                 "10.15": {                
>                     "CustomerSeed":"https://swscan.apple.com/content/catalogs/others/index-10.15customerseed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
>                     "DeveloperSeed":"https://swscan.apple.com/content/catalogs/others/index-10.15seed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
>                     "PublicSeed":"https://swscan.apple.com/content/catalogs/others/index-10.15beta-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog",
>                     "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
> #                "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-11-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
>                         },
>                 "10.14": {
>                     "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
>                         },
>                 "10.13": {
>                     "PublicRelease":"https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
>                         }
>                 }
> ```
> 
> ```
> argument="$1"
> case $argument in
>     -h|--help)
>         print_usage
>         ;;
>     -s|--high-sierra)
>         "$TOOLS/FetchMacOS/fetch.sh" -v 10.13 || exit 1;
>         ;;
>     -m|--mojave)
>         "$TOOLS/FetchMacOS/fetch.sh" -v 10.14 || exit 1;
>         ;;
>     -b|--bigsur)
>         "$TOOLS/FetchMacOS/fetch.sh" -v 10.16 || exit 1;
>         ;;
>     -d|--bigsurd)
>         "$TOOLS/FetchMacOS/fetch.sh" -v 11 || exit 1;
>         ;;        
>     -c|--catalina|*)
>         "$TOOLS/FetchMacOS/fetch.sh" -v 10.15 || exit 1;
>         ;;
> esac
> ```
> 
> Result is for using the option -d or -b is:
> 2021-01-04 18:27:09,403 Network Request: Fetching http://swcdn.apple.com/content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/InstallAssistantAuto.smd
> Traceback (most recent call last):
> File "fetch-macos.py", line 171, in
> fetchmacos()
> File "/usr/lib/python3/dist-packages/click/core.py", line 764, in **call**
> return self.main(*args, **kwargs)
> File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
> rv = self.invoke(ctx)
> File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
> return callback(*args, **kwargs)
> File "fetch-macos.py", line 156, in fetchmacos
> product_id = remote.getosinstall()[0]
> IndexError: list index out of range
> 
> I also tried to create a harddisk with installer of big sur. The installation from this disk is also not working with simple-kvm because starting the big sur installer harddisk the vm will stuck in boot process. The same disk with big sur installer will work with OSX-KVM. But OSX-KVM has horrible graphics performance and no sound.

You don't see anything wrong with this section?

    -b|--bigsur)
        "$TOOLS/FetchMacOS/fetch.sh" -v 10.16 || exit 1;
        ;;
    -d|--bigsurd)
        "$TOOLS/FetchMacOS/fetch.sh" -v 11 || exit 1;

Is BigSur version 10.16 or version 11?
And why bigsurd?

**Comment by nemihome** [comment]
Correct me If I'm wrong but I think the -b|--bigsur are just placeholder for selection of the installer in command line. Could also be -1|--one or whatever. The question 10.16 / 11 is not so easy. That's the reason why I tried both. There are catalogs for 10.16 and 11. I think in beta apple used the name 10.16 and with release 11. Both links in the upper section are working. Which means the 10.16 and the 11 catalogue are existing. In my opinion 11 should be correct. 

The fetch-macos.py 156 does not look special to me. The other sections seem to be standard python code.
