### ISSUE TITLE
No module named 'click'

### ISSUE THREAD

**Issue by UnixCro** [foxlet/macOS-Simple-KVM#399]
```
./jumpstart.sh --high-sierra 

Requirement already satisfied: requests in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: click in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (7.1.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/user/Library/Python/3.9/lib/python/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests->-r requirements.txt (line 1)) (1.25.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/user/Library/Python/3.9/lib/python/site-packages (from requests->-r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests->-r requirements.txt (line 1)) (2.8)

Traceback (most recent call last):
  File "fetch-macos.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by auscyber** [comment]
Just type
python3 -m pip install click

**Comment by UnixCro** [comment]
Thanks worked, can you tell me why pip3 install click didn't work?

```
pip3 install click                  
Requirement already satisfied: click in /usr/local/lib/python3.9/site-packages (7.1.2)

./jumpstart.sh --high-sierra 
Traceback (most recent call last):
  File "fetch-macos.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

```
sudo python3  -m pip install click
Collecting click
  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
Installing collected packages: click
Successfully installed click-7.1.2
```
Edit: I just noticed that the next mistake was revealed.
`./jumpstart.sh: line 39: /Users/user/macOS-Simple-KVM/tools/dmg2img: cannot execute binary file`
macOS Catalina 10.15.7

**Comment by shawnhank** [comment]
This is for anyone else who has run into:

`"./jumpstart.sh: line 39: /Users/user/macOS-Simple-KVM/tools/dmg2img: cannot execute binary file"`

Context:

I installed macOS-Simple-KVM via GitHub CLI. That put the macOS-Simple-KVM folder in my /Users/<username> directory.  If you installed macOS-Simple-KVM using a different method, change the tools folder so it matches your location & setup.

Fix:
1. In /Users/<username>/macOS-Simple-KVM/tools > renamed dmg2img binary to dmg2img.old 

`mv dmg2img dmg2img.old`

2. Installed a different version of dmg2img using brew:

`brew install dmg2img`

3. Copy the 2 files (dmg2img & vfdecrypt) from the brew install directory
`cp /usr/local/Cellar/dmg2img/1.6.7_1/bin/* /Users/<username>/macOS-Simple-KVM/tools/`

4. run /jumpstart.sh --mojave and you're done.
