### ISSUE TITLE
Requested operation is not valid: Setting different DAC user or group on OVMF_VARS-1024x768.fd which is already in use

### ISSUE THREAD

**Issue by jordanchaitin** [foxlet/macOS-Simple-KVM#409]
I am running MacOS Mojave via Virtual Machine Manager on Ubuntu 20.04 LTS. 

Normally it works fine, but often when I power off the VM, it seems to act up afterwards. 
```

Error starting domain: internal error: child reported (status=125): Requested operation is not valid: Setting different DAC user or group on /mnt/M/macOS-Simple-KVM/firmware/OVMF_VARS-1024x768.fd which is already in use

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1279, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1234, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: internal error: child reported (status=125): Requested operation is not valid: Setting different DAC user or group on /mnt/M/macOS-Simple-KVM/firmware/OVMF_VARS-1024x768.fd which is already in use

```

**Comment by gwillgues** [comment]
I'm having this issue as well, but instead of issues with DAC its complaining about SELinux (MAC):

`Error starting domain: Requested operation is not valid: Setting different SELinux label on /opt/data/macOS-Simple-KVM/firmware/OVMF_VARS-1024x768.fd which is already in use`
