### ISSUE TITLE
virtual machine manager -> macOS-Simple-KVM - Storage access error

### ISSUE THREAD

**Issue by stromal** [foxlet/macOS-Simple-KVM#439]
I am trying to make macos simple kvm (Mojave) with my old GTX 650 - I have installed the new gpu bios that support UEFI. When I just start the QUEMU with ./basic.sh it run but the gpu pas-thru not working aliases with the screen + it the setting/ graphic it does not shows the gpu.
I use this guide - https://passthroughpo.st/mac-os-vm-guide-part-2-gpu-passthrough-and-tweaks/
But wan I try to start it from virtual machine manager but I get the following error
Error starting domain: Cannot access storage file '/home/aa/macOS-Simple-KVM/ESP.qcow2' (as uid:65534, gid:992): Permission denied
```
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 101, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1329, in startup
    self._backend.create()
  File "/usr/lib/python3.9/site-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: Cannot access storage file '/home/aa/macOS-Simple-KVM/ESP.qcow2' (as uid:65534, gid:992): Permission denied
```
Tried
- I don't find it what this answers try to point to. I have the file but I don't know what does the answered wants me to look for. - https://bbs.archlinux.org/viewtopic.php?id=247377

**Comment by hg** [comment]
With `basic.sh` you're running qemu under your own user, so it has access to your home directory.

When starting qemu from libvirt, it appears to be running under `nobody`.

You have multiple options:

- replace `user = whatever` in `/etc/libvirt/qemu.conf` with your own user, restart libvirt, and try again. If it does not appear in the file, add `user = "your_username"` to the end of file.
- allow access to qemu user with acls (something like `setfacl -m u:nobody:rx $HOME && setfacl -R -m u:nobody:rwx $HOME/macOS-Simple-KVM`)
- move files outside of your home directory and `chown` them to `nobody`

If you're running Fedora and want to keep files in your home directory, you might also have to configure SELinux (or disable it.)

**Comment by stromal** [comment]
I use Manjaro (Arch like commands are applied).
