### ISSUE TITLE
InvalidURL: filed to parse swscan.apple.com

### ISSUE THREAD

**Issue by len0xx** [foxlet/macOS-Simple-KVM#521]
I get this error when running ./jumpstart.sh

equirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.25.1)
Requirement already satisfied: click in /home/len0xx/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (8.0.3)
2021-11-23 22:12:47,981 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 382, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/len0xx/KVM/macOS/tools/FetchMacOS/fetch-macos.py", line 158, in <module>
    fetchmacos()
  File "/home/len0xx/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/len0xx/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/len0xx/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/len0xx/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/len0xx/KVM/macOS/tools/FetchMacOS/fetch-macos.py", line 139, in fetchmacos
    catalog = remote.getcatalog()
  File "/home/len0xx/KVM/macOS/tools/FetchMacOS/fetch-macos.py", line 89, in getcatalog
    self.catalog_data = Filesystem.fetch_plist(self.catalog_url)
  File "/home/len0xx/KVM/macOS/tools/FetchMacOS/fetch-macos.py", line 54, in fetch_plist
    plist_raw = requests.get(url, headers=ClientMeta.swupdate)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 384, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog

I am using Debian 11 btw

**Comment by notAperson535** [comment]
@len0xx Use this file from my repo: https://github.com/notAperson535/OneClick-macOS-Simple-KVM/blob/master/fetch-macOS-v2.py  to download macOS. Download Catalina at most unless you want to switch to my repo, in that case just use my repo. You can get up to Monterey.

(I am trying not to make this sound like an ad for my repo)
