### ISSUE TITLE
virt-manager doesn't work

### ISSUE THREAD

**Issue by Adamekka** [foxlet/macOS-Simple-KVM#605]
basic.sh works, but virt-manager does not, below is the error, I've tried everything with permissions on that file, but it still doesn't work

![image](https://github.com/foxlet/macOS-Simple-KVM/assets/68786400/9b071e12-2f0e-4fb7-a6c1-d04560fea7cd)

```c
Error starting domain: internal error: process exited while connecting to monitor: 2023-05-29T13:32:31.909401Z qemu-system-x86_64: -blockdev {"driver":"file","filename":"/mnt/mac/macOS-Simple-KVM-master/firmware/OVMF_CODE.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"}: Could not open '/mnt/mac/macOS-Simple-KVM-master/firmware/OVMF_CODE.fd': Permission denied

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib64/python3.11/site-packages/libvirt.py", line 1362, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2023-05-29T13:32:31.909401Z qemu-system-x86_64: -blockdev {"driver":"file","filename":"/mnt/mac/macOS-Simple-KVM-master/firmware/OVMF_CODE.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"}: Could not open '/mnt/mac/macOS-Simple-KVM-master/firmware/OVMF_CODE.fd': Permission denied
```

**Comment by enderdude77** [comment]
I am having the same exact issue.

**Comment by HarshNarayanJha** [comment]
Try running using sudo

**Comment by scyilk** [comment]
As a sidenote, ```sudo !!``` will run the last command you ran with ```sudo``` if you are on bash, which it seems like you are.

**Comment by HarshNarayanJha** [comment]
> As a sidenote, `sudo !!` will run the last command you ran with `sudo` if you are on bash, which it seems like you are.

Oh Wow! Didn't know that one. Thanks
