### ISSUE TITLE
my virtual machine is not working

### ISSUE THREAD

**Issue by alessio11223344** [foxlet/macOS-Simple-KVM#624]
my virtual machine is not working error:Error starting domain: operation failed: unable to find any master var store for loader: /home/alessio/OSX-KVM/OVMF_CODE.fd
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfnret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1384, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: operation failed: unable to find any master var store for loader: /home/alessio/OSX-KVM/OVMF_CODE.fd why

**Comment by username23425** [comment]
Try `git restore firmware/OMVF_VARS.fd`
